name: Hide Sensitive Information
on: push
jobs:
  print-secret-token:
    runs-on: ubuntu-latest
    steps:
      - name: Add Mask
        run: echo "::add-mask::${{ secrets.API_KEY }}"
      - name: 'Create env file'
        run: |
          touch .env
          echo VITE_API_KEY=${{ secrets.API_KEY }} >> .env
          cat .env
